---
base_packages_default:
  - vim
  - tmux
  - zsh
  - fzf
  - git
  - direnv
  - shellcheck
  - jq
  - curl
  - wget
  - unzip
  - python3
  - python3-venv
  - python3-pip
  - ripgrep

base_packages_extra: []
