---
- name: Run role
  hosts: all
  any_errors_fatal: true
  module_defaults:
    package:
      update_cache: true
  tasks:
    - name: "Include dotfiles role"
      include_role:
        name: "../../../dotfiles"
