name: Check all the Things!

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml

  molecule:
    name: Molecule Tests
    uses: ./.github/workflows/molecule-discovery.yaml

  build-and-test:
    name: Build and Test Container
    needs:
      - molecule
      - lint
    uses: ./.github/workflows/build-and-test-sandbox.yaml

  publish:
    name: Build and Publish Container
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-push-sandbox.yaml
