name: lint
on:
  workflow_call:

jobs:
  lint-ansible:
    name: Lint ansible
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: .github/requirements.txt

      - name: Install dependencies.
        run: pip3 install -r .github/requirements.txt

      - name: Install ansible collections
        run: ansible-galaxy install -r requirements.yaml

      - name: Lint ansible code.
        run: |
          yamllint .
          ansible-lint

  lint-containerfile:
    name: Lint Containerfile
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: ./sandbox/Containerfile
          failure-threshold: warning
